# -*- coding: utf-8 -*-
"""create_df.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Kn_Un3hTVd9nzruhclS_lwXj2mZ2Ati
"""

import os, matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import pandas as pd

dataset_path = '/content/drive/MyDrive/PROJECTS/ObjectLocalization/Marvel Vs StarWars/dataset/'

classes = os.listdir(dataset_path)

xml_files = []
# jpg_files = []

for cls in classes:
    path = os.path.join(dataset_path, cls)
    all_files = os.listdir(path)
    for item in all_files:
        if item.split('.')[1] == 'xml':
            xml_files.append(os.path.join(path, item))

# file_names = []
file_paths = []
class_names = []
xmins, ymins, xmaxs, ymaxs = [], [], [], []

for item in xml_files:
    with open(item, 'r') as f:
        data = f.read()
    bs_data = BeautifulSoup(data, 'xml')
    # print(bs_data)
    
    file_name = str(bs_data.find('filename')).split('>')[1].split('<')[0]
    # file_names.append(file_name)

    class_name = str(bs_data.find('folder')).split('>')[1].split('<')[0]
    class_names.append(class_name)

    file_path = dataset_path + class_name
    file_path = os.path.join(file_path, file_name)
    file_paths.append(file_path)

    xmin = float(str(bs_data.find('xmin')).split('>')[1].split('<')[0])
    ymin = float(str(bs_data.find('ymin')).split('>')[1].split('<')[0])
    xmax = float(str(bs_data.find('xmax')).split('>')[1].split('<')[0])
    ymax = float(str(bs_data.find('ymax')).split('>')[1].split('<')[0])

    xmins.append(xmin)
    ymins.append(ymin)
    xmaxs.append(xmax)
    ymaxs.append(ymax)

df_ = {
    'image_path':file_paths,
    'class':class_names,
    'xmin':xmins,
    'ymin':ymins,
    'xmax':xmaxs,
    'ymax':ymaxs
}

df = pd.DataFrame(df_)

class_df = pd.get_dummies(df['class'].values)
img_df = df.iloc[:, [0]]
coordinate_df = df.iloc[:, 2:]

df_final = pd.concat([img_df, class_df, coordinate_df], axis=1)

df_final.to_csv('/content/drive/MyDrive/PROJECTS/ObjectLocalization/Marvel Vs StarWars/df.csv', index=False)















