# -*- coding: utf-8 -*-
"""Models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a423ZTIUin76hWoGqwwG_TLFBZnaLyjo
"""

import torch.nn as nn
import torch
import torchvision

def ResNet18(df, device='cuda', pretrained_weights=True):
    model = torchvision.models.resnet18(pretrained=pretrained_weights)
    model.fc = nn.Linear(
        in_features=model.fc.in_features,
        out_features=len(df.iloc[0, 1:].values)
    )
    model.to(device)
    return model

























